--DROPS OLD TABLES
DROP TABLE IF EXISTS dbo.PakanHarian;
DROP TABLE IF EXISTS dbo.AirHarian;
DROP TABLE IF EXISTS dbo.Panen;
DROP TABLE IF EXISTS dbo.Tebar; 
DROP TABLE IF EXISTS dbo.Petak; 
DROP TABLE IF EXISTS dbo.Pakan; 
DROP TABLE IF EXISTS dbo.Users; 

--CREATE TABLES NEEDED FOR THE SYSTEM
CREATE TABLE dbo.Petak 
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	NoPetak VARCHAR(10)
);

CREATE TABLE dbo.Users 
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Username VARCHAR(20) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Nama VARCHAR(50) NOT NULL
);

CREATE TABLE dbo.Tebar
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	PetakId INT NOT NULL FOREIGN KEY REFERENCES Petak(Id),
	JumlahKantong INT NOT NULL,
	BenihPerKantong INT NOT NULL,
	BeratKantong INT NOT NULL,
	Tanggal DATE NOT NULL
);

CREATE TABLE dbo.Pakan
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Nama VARCHAR(25) NOT NULL,
	Stok INT NOT NULL,
);

CREATE TABLE dbo.PakanHarian
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	PetakId INT NOT NULL FOREIGN KEY REFERENCES Petak(Id),
	PakanId INT NOT NULL FOREIGN KEY REFERENCES Pakan(Id),
	Quantity FLOAT NOT NULL,
	Tanggal DATE NOT NULL
);

CREATE TABLE dbo.AirHarian
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	PetakId INT NOT NULL FOREIGN KEY REFERENCES Petak(Id),
	Alga FLOAT NOT NULL,
	PH FLOAT NOT NULL,
	Obat FLOAT NOT NULL,
	Kaporit FLOAT NOT NULL,
	Tanggal DATE NOT NULL
);

CREATE TABLE dbo.Panen
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY, 
	PetakId INT NOT NULL FOREIGN KEY REFERENCES Petak(Id),
	BeratTotal FLOAT NOT NULL,
	BeratKerusakan FLOAT NOT NULL,
	Tanggal DATE NOT NULl
);

--INSERT SOME DEFAULT DATA
INSERT INTO 
	dbo.Users (Username, Password, Nama)
VALUES
	('admin', 'situpAssw0rd', 'Rakandhiyaa');